### ISSUE TITLE
JSONDecodeError simplejson.decoder in raw_decode

### ISSUE THREAD

**Issue by buckyroberts** [thenewboston-developers/Validator#64]
**Update:** 
I believe this is due to calling an old endpoint here https://github.com/thenewboston-developers/Validator/blob/master/v1/tasks/sync_with_primary_validator.py#L38

The new shape may be `confirmation_blocks/{block_identifier}/valid` if I remember correctly? @fonar can you please take a look into this?

![screencapture-sentry-io-organizations-thenewboston-issues-1943278571-2020-10-07-22_39_09](https://user-images.githubusercontent.com/8547538/95419239-13a8cb80-08ee-11eb-8ac5-568ff4d8ed5e.png)

**Comment by vosi** [comment]
@buckyroberts that ticket actually should be on thenewboston-python repo
the other thing, it's not actually a bug, as you have a wide try except there, and i've just added a tracking when including sentry... since wide exceptions are generally discouraged

the problem is ... from the `thenewboston.utils.network.validate_response`
```
def validate_response(response):
    """
    Validate status code
    Return response as Python object
    """

    data = response.json()

    if response.status_code >= 400:
        err = f'status_code:{response.status_code} - {data}'
        raise NetworkException(err)

    return data
```
`data = response.json()` should be AFTER if block

**Comment by shahraizali** [comment]
This seems to be calling the endpoint
`/valid_confirmation_blocks/*****`

but I am unable to find this endpoint, in which project it should be? 
That seems to be causing this issue if you see the response its a 404 page not found HTML response which cannot be parsed in JSON ofcouse.

There do exist a '/meta/valid_confirmation_blocks/" endpoint but that just returns all_valid_confirmation_blocks.

Although there should be exception handling on the `data = response.json()` block for non-JSON responses but this specific issue is because either that URL does not exist or it's not resolving to any class or function.
@buckyroberts @vosi

**Comment by shahraizali** [comment]
@vosi You are right it should be after the if block so that if the response is 400 or above like, in this case, its 404 it will raise an exception before reaching this line. However, it's logging the response data which I think is not ideal here. should I remove that data attribute from that string? What do you guys suggest?

**Comment by fonar** [comment]
@buckyroberts @vosi @shahraizali 
looks like that issue is solved today PR by https://github.com/thenewboston-developers/thenewboston-python/pull/22
and we can merge and close?

**Comment by buckyroberts** [comment]
@fonar that PR is just to improve the error handling, it doesn't fix why this error happened in the first place. The error occurred because this endpoint no longer exists https://github.com/thenewboston-developers/Validator/blob/master/v1/tasks/sync_with_primary_validator.py#L38

**Comment by fonar** [comment]
@buckyroberts big sorry, don't know why, but i missed notification when you mentioned me in this ticket last week,
looks like fixed now.
